### ISSUE TITLE
分享一下自己汇总的裕兴学习机机型的简要信息

### ISSUE THREAD

**Issue by Tsubamei** [Target620/ZWDNXXJ-Wiki#1]
![PixPin_2024-06-16_06-57-33](https://github.com/Target620/ZWDNXXJ-Wiki/assets/61179776/7c83ec48-96c7-4e03-ab0e-7d72f7b30ffd)

**Comment by Target620** [comment]
已阅，抽时间写进Wiki里面。

**Comment by Target620** [comment]
一口气把所有机型都加了页面。

如果想补充可以直接在条目改。
